# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096c4472a42ad66ce33d58ae2b8c7253368674cc3bd50066141b66cc819bdb7feb8bbdb8be9f6e6452604bdd0ebbcdfde0c7c6ec77aff1f186403760ec6bce63

test:
  secret_key_base: 06fbe174cf645ff5ca3f87dffc90163aaa6adddfa4bf8d36025f77840a277d33ec3556a39f0175d74bc061975e54694b8efb964d9c6bd2e6dc09f7837fd1bb6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
